### ISSUE TITLE
MINOR: input validation for color converter

### ISSUE THREAD

**Issue by Segelzwerg** [Segelzwerg/django-dynamic-theme#59]
After the merge of #41  the color converter requires checks for valid inputs of HEX color strings.

**Comment by HealthyDoggo** [comment]
How do you want the error to be thrown if an input passed is not a valid HEX color string?

**Comment by Segelzwerg** [comment]
> How do you want the error to be thrown if an input passed is not a valid HEX color string?

Hi @HealthyDoggo thanks for contributing.

How about we create a custom error that is called something NonHexValueError?

**Comment by HealthyDoggo** [comment]
Sounds good.
